[plugin]
repository = "https://github.com/WesselKuipers/FCNameColor.git"
commit = "425db516253ce8fb7780b9184f47b105f8588ef2"
owners = ["WesselKuipers"]
project_path = "FCNameColor"
changelog = """
- Update for 6.3
- Make the plugin respect the user's name display types based on their settings.
  Names will correctly abbreviate based on your settings for others/party members/alliance members/friends.
"""