[plugin]
repository = "https://github.com/WesselKuipers/FCNameColor.git"
commit = "dc653477f07b553d5baf6fb3c28335d04a331caf"
owners = ["WesselKuipers"]
project_path = "FCNameColor"
changelog = """
- Update for 6.2
- Use different hooking mechanism
- Add option to make FCNC only work inside duties.

The new hooking mechanism will cause conflicts with other plugins that change nameplates.
For the time being you can use the "Only duties" option if you’re using something else outside of them.
"""